import inspect
import typing

import pydantic

from .compressed_save_file_body import CSaveFileBody, CSaveFileChunk
from .level import Level
from .level_grouping_grid import (
    GridName,
    LevelGroupingGrid,
    LevelInfo,
)
from .level_object import (
    ActorObject,
    ComponentObject,
    LevelObjectType,
    deserialize_level_object,
)
from .object_header import (
    ActorHeader,
    ComponentHeader,
    HeaderType,
    ObjectHeaderType,
    Quaternion,
    Vector3,
    deserialize_object_header,
    serialize_object_header,
)
from .object_reference import ObjectReference
from .properties import (
    ArrayElementByte,
    ArrayElementEnum,
    ArrayElementFloat,
    ArrayElementInt,
    ArrayElementInt64,
    ArrayElementInterface,
    ArrayElementObject,
    ArrayElementSoftObject,
    ArrayElementStr,
    ArrayElementStruct,
    ArrayElementStructValueType,
    ArrayElementType,
    ArrayElementTypeName,
    ArrayProperty,
    BaseArrayElement,
    BaseProperty,
    BoolProperty,
    Box,
    ByteProperty,
    ClientIdentityInfo,
    ClientIdentityInfoIdentity,
    ClientIdentityInfoIdentityVariant,
    DateTime,
    DoubleProperty,
    EnumProperty,
    FloatProperty,
    FluidBox,
    Int8Property,
    Int64Property,
    IntProperty,
    InventoryItem,
    KeyTypeName,
    LinearColor,
    MapKeyType,
    MapKeyValue,
    MapProperty,
    NameProperty,
    ObjectProperty,
    PropertyType,
    PropertyTypeName,
    Quat,
    RailroadTrackPosition,
    SetProperty,
    SetType,
    SoftObjectProperty,
    SpawnData,
    StrProperty,
    StructProperty,
    StructTypeName,
    TextArgument,
    TextArgumentInt,
    TextArgumentText,
    TextArgumentType,
    TextProperty,
    TextPropertyHistoryType,
    TextValue,
    TextValueBase,
    TextValueNone,
    TextValueStringTableEntry,
    TextValueTransform,
    TextValueWithArguments,
    UInt32Property,
    ValueTypeName,
    Vector,
    deserialize_properties,
    deserialize_text_argument,
)
from .save_file_body import SaveFileBody
from .save_file_header import SaveFileHeader, SessionVisibility

__all__ = (
    "ActorHeader",
    "ActorObject",
    "ArrayElementByte",
    "ArrayElementEnum",
    "ArrayElementFloat",
    "ArrayElementInt",
    "ArrayElementInt64",
    "ArrayElementInterface",
    "ArrayElementObject",
    "ArrayElementSoftObject",
    "ArrayElementStr",
    "ArrayElementStruct",
    "ArrayElementStructValueType",
    "ArrayElementType",
    "ArrayElementTypeName",
    "ArrayProperty",
    "BaseArrayElement",
    "BaseProperty",
    "BoolProperty",
    "Box",
    "ByteProperty",
    "CSaveFileBody",
    "CSaveFileChunk",
    "ClientIdentityInfo",
    "ClientIdentityInfoIdentity",
    "ClientIdentityInfoIdentityVariant",
    "ComponentHeader",
    "ComponentObject",
    "DateTime",
    "DoubleProperty",
    "EnumProperty",
    "FloatProperty",
    "FluidBox",
    "GridName",
    "HeaderType",
    "Int8Property",
    "Int64Property",
    "IntProperty",
    "InventoryItem",
    "KeyTypeName",
    "Level",
    "LevelGroupingGrid",
    "LevelInfo",
    "LevelObjectType",
    "LinearColor",
    "MapKeyType",
    "MapKeyValue",
    "MapProperty",
    "NameProperty",
    "ObjectHeaderType",
    "ObjectProperty",
    "ObjectReference",
    "PropertyType",
    "PropertyTypeName",
    "Quat",
    "Quaternion",
    "RailroadTrackPosition",
    "SaveFileBody",
    "SaveFileHeader",
    "SessionVisibility",
    "SetProperty",
    "SetType",
    "SoftObjectProperty",
    "SpawnData",
    "StrProperty",
    "StructProperty",
    "StructTypeName",
    "TextArgument",
    "TextArgumentInt",
    "TextArgumentText",
    "TextArgumentType",
    "TextProperty",
    "TextPropertyHistoryType",
    "TextValue",
    "TextValueBase",
    "TextValueNone",
    "TextValueStringTableEntry",
    "TextValueTransform",
    "TextValueWithArguments",
    "UInt32Property",
    "ValueTypeName",
    "Vector",
    "Vector3",
    "deserialize_level_object",
    "deserialize_object_header",
    "deserialize_properties",
    "deserialize_text_argument",
    "serialize_object_header",
)


for item_cls in filter(
    lambda item: inspect.isclass(item) and issubclass(item, pydantic.BaseModel),
    {**locals(), **globals()}.values(),
):
    typing.cast("type[pydantic.BaseModel]", item_cls).model_rebuild()
